service: lambda-test # NOTE: update this with your service name
provider:
  name: aws
  runtime: nodejs6.10
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get
  functionA:
    handler: handler.functionA
    events:
      - http:
          path: /functionA
          method: get
  functionB:
    handler: handler.functionB
    events:
      - http:
          path: /functionB
          method: get