service: lambda-test # NOTE: update this with your service name
provider:
  name: aws
  runtime: nodejs6.10
functions:
  start_agent:
    handler: handler.start_agent
    events:
      - http:
          path: /start_agent
          method: post